### ISSUE TITLE
Разбивать полигон на части

### ISSUE THREAD

**Issue by rendrom** [myrov01/geotools#4]
Разработать алгоритм, который позволяет делить исходный полигон на части таким образом, чтобы в каждом из полученных фрагментов количество вершин не превышало заданного значения.

Например:
Деление начинается с разреза полигона по вертикали. При этом, в зависимости от формы полигона, может образоваться больше двух частей, например, в случае со сложной геометрией, такой как спираль. После разреза подсчитывается количество вершин в каждой части. Те фрагменты, где количество вершин превышает заданное значение, делятся дальше, но уже по горизонтали. Этот процесс повторяется, чередуя вертикальные и горизонтальные разрезы, до тех пор, пока в каждом из новых полигонов не окажется количество вершин, не превышающее установленного лимита.

**Comment by myrov01** [comment]
@rendrom помог реализовать таск. Закрываю.
